# Default Configuration (Development)
server.port=8080

# Default to localhost for development
cors.allowed-origins=http://localhost:4200

# Verbose logging for development debugging
logging.level.org.springframework.web=INFO
logging.level.com.personalwebsite.backend=DEBUG
